name: C Project CI
on:
  push:
    branches: [ "master" ]
  # Used for building/testing the PR code safely
  pull_request:
    branches: [ "master" ]
  # Used for running actions that need write access (like storing benchmarks)
  pull_request_target:
    branches: [ "master" ]

# Default permissions (kept restrictive globally)
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    # Only run this job if it's a push or a standard pull_request (to avoid duplication)
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    # NOTE: We rely on the restrictive global permissions here. Do not add 'contents: write'.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libapr1-dev \
            libaprutil1-dev \
            libpcre3-dev \
            check \
            lcov \
            subunit \
            python3-junitxml
      - name: Configure build
        run: |
          autoreconf -i
          ./configure --enable-coverage
      - name: Run tests and generate reports
        run: |
          make junit
          make benchmark
          make coverage

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'reports/junit.xml'
          check_name: 'Unit Test Results'
          fail_on_failure: true

      - name: Publish Code Coverage Report
        uses: zgosalvez/github-actions-report-lcov@v4
        if: always()
        with:
          coverage-files: reports/coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Upload Benchmark JSON Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # Use this specific name as it's expected by the process-benchmarks job
          name: benchmark-results
          path: reports/benchmarks.json

      - name: Upload HTML Coverage Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-html
          path: reports/coverage/

      - name: Upload JUnit XML Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-results-xml
          path: reports/junit.xml

  # Job to handle benchmark storage with elevated permissions
  process-benchmarks:
    needs: build-and-test
    # Run this job if it's a push or pull_request_target
    if: github.event_name == 'push' || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push benchmark history to gh-pages
      pull-requests: write # Required to post comments on PRs
    steps:
      # Download the artifact generated by the previous job
      - name: Download Benchmark Artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results
          # Download into the expected directory structure
          path: reports/

      - name: Store benchmark data for regression analysis
        uses: benchmark-action/github-action-benchmark@v1
        with:
          output-file-path: 'reports/benchmarks.json'
          tool: 'customBiggerIsBetter'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          alert-threshold: '150%'
          # Enable auto-push (will work now due to correct permissions/triggers)
          auto-push: true
          # CRITICAL: Ensure the action associates results with the PR's head commit SHA
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

  deploy-pages:
    needs: build-and-test
    # Ensure this runs only on push to the master branch
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-html
          path: ./coverage-report
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './coverage-report'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
